<?php
$sei=$_POST['sei'];
$mei=$_POST['mei'];
$sei_kana=$_POST['sei_kana'];
$mei_kana=$_POST['mei_kana'];
$address1=$_POST['address1'];
$address2=$_POST['address2'];
$email=$_POST['email'];
$password=$_POST['password'];
$password2=$_POST['password2'];
 include("./comfirm.html");
?>